version: '3.8'
services:
  angular_app:
    build:
      context: .
      target: production
    image: angular-playground:prod
    container_name: angular_app
    restart: always
    expose:
      - "4000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:1.25-alpine
    container_name: angular_nginx
    depends_on:
      - angular_app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/angular-playground/browser:/usr/share/nginx/html/browser:ro
    restart: always
